server:
  port: 8086
spring:
  application:
    name: yunzhang-download #指定服务名
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://122.51.105.58:3306/yunzhang?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: '@asdend123'
    jpa:
      database: MySQL
      show-sql: true
    redis:
      host: 122.51.105.58
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
mybatis:
  mapper-locations: com/owwang/yunzhang/dao/*.xml
  type-aliases-package: com.owwang.yunzhang.pojo